import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatisticsChart } from "@/components/charts/StatisticsChart";
import { DataTable } from "@/components/tables/DataTable";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileText, Download, Printer } from "lucide-react";

// Mock report data
const reportData = [
  {
    id: "1",
    title: "Monthly Crime Statistics",
    generated_by: "System",
    date: "2025-03-01",
    type: "Monthly Report",
    status: "Ready",
  },
  {
    id: "2",
    title: "Officer Performance Report",
    generated_by: "Station Admin",
    date: "2025-03-15",
    type: "Performance Report",
    status: "Ready",
  },
  {
    id: "3",
    title: "Resource Utilization",
    generated_by: "System",
    date: "2025-03-20",
    type: "Resource Report",
    status: "Ready", 
  },
  {
    id: "4",
    title: "Case Resolution Time",
    generated_by: "Station Admin",
    date: "2025-03-25",
    type: "Performance Report",
    status: "Processing",
  },
  {
    id: "5",
    title: "Patrol Coverage Analysis",
    generated_by: "System",
    date: "2025-03-28",
    type: "Patrol Report",
    status: "Ready",
  },
];

// Monthly crime statistics
const monthlyCrimeData = [
  { name: "Jan", count: 22 },
  { name: "Feb", count: 28 },
  { name: "Mar", count: 32 },
  { name: "Apr", count: 24 },
  { name: "May", count: 18 },
  { name: "Jun", count: 25 },
  { name: "Jul", count: 30 },
  { name: "Aug", count: 27 },
  { name: "Sep", count: 24 },
  { name: "Oct", count: 28 },
  { name: "Nov", count: 33 },
  { name: "Dec", count: 36 },
];

export default function StationReportsPage() {
  const handleViewReport = (id: string) => {
    console.log("View report:", id);
    // Navigate to report details
  };

  const handleDownloadReport = (id: string) => {
    console.log("Download report:", id);
    // Download report logic
  };

  const handlePrintReport = (id: string) => {
    console.log("Print report:", id);
    // Print report logic
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold">Reports</h2>
        <Button>Generate New Report</Button>
      </div>
      
      <Tabs defaultValue="all">
        <TabsList>
          <TabsTrigger value="all">All Reports</TabsTrigger>
          <TabsTrigger value="monthly">Monthly Reports</TabsTrigger>
          <TabsTrigger value="performance">Performance Reports</TabsTrigger>
          <TabsTrigger value="resource">Resource Reports</TabsTrigger>
        </TabsList>
        
        <TabsContent value="all" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Available Reports</CardTitle>
            </CardHeader>
            <CardContent>
              <DataTable
                data={reportData}
                columns={[
                  {
                    key: "title",
                    header: "Report Title",
                    cell: (item) => (
                      <div className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-blue-600" />
                        <span className="font-medium">{item.title}</span>
                      </div>
                    ),
                  },
                  {
                    key: "date",
                    header: "Date Generated",
                    cell: (item) => item.date,
                  },
                  {
                    key: "type",
                    header: "Report Type",
                    cell: (item) => item.type,
                  },
                  {
                    key: "generated_by",
                    header: "Generated By",
                    cell: (item) => item.generated_by,
                  },
                  {
                    key: "status",
                    header: "Status",
                    cell: (item) => (
                      <span
                        className={`px-2 py-1 rounded-full text-xs font-medium ${
                          item.status === "Ready" ? "bg-green-100 text-green-800" : 
                          "bg-yellow-100 text-yellow-800"
                        }`}
                      >
                        {item.status}
                      </span>
                    ),
                  },
                  {
                    key: "actions",
                    header: "Actions",
                    cell: (item) => (
                      <div className="flex gap-2">
                        <Button 
                          size="sm" 
                          variant="outline" 
                          onClick={() => handleViewReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          View
                        </Button>
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => handleDownloadReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => handlePrintReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          <Printer className="h-4 w-4" />
                        </Button>
                      </div>
                    ),
                  },
                ]}
              />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="monthly" className="mt-6">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <Card>
                <CardHeader>
                  <CardTitle>Monthly Crime Trends</CardTitle>
                </CardHeader>
                <CardContent className="h-80">
                  <StatisticsChart 
                    title="Monthly Crime Statistics"
                    type="line"
                    data={monthlyCrimeData}
                    dataKeys={["count"]}
                    colors={["#3b82f6"]}
                  />
                </CardContent>
              </Card>
            </div>
            <div>
              <Card>
                <CardHeader>
                  <CardTitle>Monthly Reports</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-4">
                    {reportData
                      .filter(report => report.type === "Monthly Report")
                      .map(report => (
                        <li 
                          key={report.id} 
                          className="flex justify-between items-center border-b pb-2"
                        >
                          <div>
                            <p className="font-medium">{report.title}</p>
                            <p className="text-sm text-gray-500">{report.date}</p>
                          </div>
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => handleViewReport(report.id)}
                          >
                            View
                          </Button>
                        </li>
                      ))}
                  </ul>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>
        
        {/* Other Tabs Content would be similar */}
        <TabsContent value="performance" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Performance Reports</CardTitle>
            </CardHeader>
            <CardContent>
              <DataTable
                data={reportData.filter(r => r.type === "Performance Report")}
                columns={[
                  {
                    key: "title",
                    header: "Report Title",
                    cell: (item) => (
                      <div className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-blue-600" />
                        <span className="font-medium">{item.title}</span>
                      </div>
                    ),
                  },
                  {
                    key: "date",
                    header: "Date Generated",
                    cell: (item) => item.date,
                  },
                  {
                    key: "actions",
                    header: "Actions",
                    cell: (item) => (
                      <div className="flex gap-2">
                        <Button 
                          size="sm" 
                          variant="outline" 
                          onClick={() => handleViewReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          View
                        </Button>
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => handleDownloadReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                      </div>
                    ),
                  },
                ]}
              />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="resource" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Resource Reports</CardTitle>
            </CardHeader>
            <CardContent>
              <DataTable
                data={reportData.filter(r => r.type === "Resource Report")}
                columns={[
                  {
                    key: "title",
                    header: "Report Title",
                    cell: (item) => (
                      <div className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-blue-600" />
                        <span className="font-medium">{item.title}</span>
                      </div>
                    ),
                  },
                  {
                    key: "date",
                    header: "Date Generated",
                    cell: (item) => item.date,
                  },
                  {
                    key: "actions",
                    header: "Actions",
                    cell: (item) => (
                      <div className="flex gap-2">
                        <Button 
                          size="sm" 
                          variant="outline" 
                          onClick={() => handleViewReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          View
                        </Button>
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => handleDownloadReport(item.id)}
                          disabled={item.status !== "Ready"}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                      </div>
                    ),
                  },
                ]}
              />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
